/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2018-10-11 19:03:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class principalExtranet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/Renzo/Desktop/RapidCargoT3_Programas_Refactorizado/RapidCargoT3Web_Ref/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/1.1.Web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("jar:file:/C:/Users/Renzo/Desktop/RapidCargoT3_Programas_Refactorizado/RapidCargoT3Web_Ref/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/1.1.Web/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1329420532000L));
    _jspx_dependants.put("jar:file:/C:/Users/Renzo/Desktop/RapidCargoT3_Programas_Refactorizado/RapidCargoT3Web_Ref/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/1.1.Web/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1329420532000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1539192289711L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar", Long.valueOf(1539192284315L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>Rapid Cargo EIRL</title>\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Twitter Cards integration: https://dev.twitter.com/cards/  -->\r\n");
      out.write("  <meta name=\"twitter:card\" content=\"summary\">\r\n");
      out.write("  <meta name=\"twitter:site\" content=\"\">\r\n");
      out.write("  <meta name=\"twitter:title\" content=\"\">\r\n");
      out.write("  <meta name=\"twitter:description\" content=\"\">\r\n");
      out.write("  <meta name=\"twitter:image\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Fav and touch icons -->\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${icons}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/favicon.png\">\r\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${icons}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/114x114.png\">\r\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${icons}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/72x72.png\">\r\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${icons}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/default.png\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap CSS File -->\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Libraries CSS Files -->\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Main Stylesheet File -->\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maincss}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!--Your custom colour override - predefined colours are: colour-blue.css, colour-green.css, colour-lavander.css, orange is default-->\r\n");
      out.write("  <link href=\"#\" id=\"colour-scheme\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("    Theme Name: Flexor\r\n");
      out.write("    Theme URL: https://bootstrapmade.com/flexor-free-multipurpose-bootstrap-template/\r\n");
      out.write("    Author: BootstrapMade.com\r\n");
      out.write("    Author URL: https://bootstrapmade.com\r\n");
      out.write("  ======================================================= -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"page-index has-hero\">\r\n");
      out.write("  <!--Change the background class to alter background image, options are: benches, boots, buildings, city, metro -->\r\n");
      out.write("  <div id=\"background-wrapper\" class=\"buildings\" data-stellar-background-ratio=\"0.1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ======== @Region: #navigation ======== -->\r\n");
      out.write("    <div id=\"navigation\" class=\"wrapper\">\r\n");
      out.write("      <!--Header & navbar-branding region-->\r\n");
      out.write("      <div class=\"header\">\r\n");
      out.write("        <div class=\"header-inner container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-8\">\r\n");
      out.write("              <!--navbar-branding/logo - hidden image tag & site name so things like Facebook to pick up, actual logo set via CSS for flexibility -->\r\n");
      out.write("              <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" title=\"Home\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--header rightside-->\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("              <!--user menu-->\r\n");
      out.write("              <ul class=\"list-inline user-menu pull-right\">\r\n");
      out.write("                <li class=\"\"><i class=\"fa fa-sign-in text-primary\"></i> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"text-uppercase\">Login</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar navbar-default\">\r\n");
      out.write("          <!--mobile collapse menu button-->\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\".navbar-collapse\" aria-expanded=\"false\"> <span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\r\n");
      out.write("          <!--social media icons-->\r\n");
      out.write("          <div class=\"navbar-text social-media social-media-inline pull-right\">\r\n");
      out.write("            <!--@todo: replace with company social media details-->\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--everything within this div is collapsed on mobile-->\r\n");
      out.write("          <div class=\"navbar-collapse collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\" id=\"main-menu\">\r\n");
      out.write("              <li class=\"icon-link\">\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"><i class=\"fa fa-home\"></i></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li><a href=\"#\">Seguimiento</a></li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">Sobre Nosotros</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"#\">Contacto</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--/.navbar-collapse -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hero\" id=\"highlighted\">\r\n");
      out.write("      <div class=\"inner\">\r\n");
      out.write("        <!--Slideshow-->\r\n");
      out.write("        <div id=\"highlighted-slider\" class=\"container\">\r\n");
      out.write("          <div class=\"item-slider\" data-toggle=\"owlcarousel\" data-owlcarousel-settings='{\"singleItem\":true, \"navigation\":true, \"transitionStyle\":\"fadeUp\"}'>\r\n");
      out.write("            <!--Slideshow content-->\r\n");
      out.write("            <!--Slide 1-->\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 col-md-push-6 item-caption\">\r\n");
      out.write("                  <h2 class=\"h1 text-weight-light\">\r\n");
      out.write("                     <span class=\"text-primary\">Rapid Cargo</span>\r\n");
      out.write("                    </h2>\r\n");
      out.write("                  <h4>\r\n");
      out.write("                      Envío de encomiendas en las ciudades más importantes del país. 100% garantizado.\r\n");
      out.write("                    </h4>\r\n");
      out.write("                  <p>Nos consolidamos como una de las empresas más serias en todo el pais debido al \r\n");
      out.write("                     compromiso que tenemos con cada uno de nuestros clientes y sus encomiendas,\r\n");
      out.write("                     garantizando la seguridad de las mismas en todo momento. </p>\r\n");
      out.write("                  <a href=\"https://bootstrapmade.com\" class=\"btn btn-more btn-lg i-right\">Envía ahora <i class=\"fa fa-plus\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-md-pull-6 hidden-xs\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/slides/slide3.png\" alt=\"Slide 1\" class=\"center-block img-responsive\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <!-- ======== @Region: #content ======== -->\r\n");
      out.write("  <div id=\"content\">\r\n");
      out.write("    <!-- Services -->\r\n");
      out.write("    <div class=\"services block block-bg-gradient block-border-bottom\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2 class=\"block-title\">\r\n");
      out.write("            Nuestros servicios\r\n");
      out.write("          </h2>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4 text-center\">\r\n");
      out.write("            <span class=\"fa-stack fa-5x\">\r\n");
      out.write("              <i class=\"fa fa-circle fa-stack-2x text-primary\"></i>\r\n");
      out.write("              <i class=\"fa fa-group fa-stack-1x fa-inverse\"></i> </span>\r\n");
      out.write("            <h4 class=\"text-weight-strong\">\r\n");
      out.write("                Veloces como el rayo\r\n");
      out.write("              </h4>\r\n");
      out.write("            <p>Entregamos sus encomiendas en un rango de entre 24-48 horas después de que usted lo envía.</p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#\" class=\"btn btn-more i-right\">Leer más <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 text-center\">\r\n");
      out.write("            <span class=\"fa-stack fa-5x\">\r\n");
      out.write("              <i class=\"fa fa-circle fa-stack-2x text-primary\"></i>\r\n");
      out.write("              <i class=\"fa fa-pencil fa-stack-1x fa-inverse\"></i> </span>\r\n");
      out.write("            <h4 class=\"text-weight-strong\">\r\n");
      out.write("                ¿Alguien dijo caro?\r\n");
      out.write("              </h4>\r\n");
      out.write("            <p>En RapidCargo Encomiendas pensamos que no tiene porqué pagar más por un buen servicio. Usted merece tenerlo por un precio justo.</p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#\" class=\"btn btn-more i-right\">Leer más <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 text-center\">\r\n");
      out.write("            <span class=\"fa-stack fa-5x\">\r\n");
      out.write("              <i class=\"fa fa-circle fa-stack-2x text-primary\"></i>\r\n");
      out.write("              <i class=\"fa fa-cogs fa-stack-1x fa-inverse\"></i> </span>\r\n");
      out.write("            <h4 class=\"text-weight-strong\">\r\n");
      out.write("                Su pedido bajo siete llaves\r\n");
      out.write("              </h4>\r\n");
      out.write("            <p> Cuando usted envía algo con nosotros, puede tener la confianza de que no se perderá o llegará dañado. </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#\" class=\"btn btn-more i-right\">Leer más <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("  <!-- ======== @Region: #footer ======== -->\r\n");
      out.write("  <footer id=\"footer\" class=\"block block-bg-grey-dark\" data-block-bg-img=\"img/bg_footer-map.png\" data-stellar-background-ratio=\"0.4\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\" id=\"contact\">\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <address>\r\n");
      out.write("              <strong>Rapid Cargo Encomiendas EIRL</strong>\r\n");
      out.write("              <br>\r\n");
      out.write("              <i class=\"fa fa-map-pin fa-fw text-primary\"></i> Jr. Las Amatistas 1123 - Surco, Lima, Perú\r\n");
      out.write("              <br>\r\n");
      out.write("              <i class=\"fa fa-phone fa-fw text-primary\"></i> 019223 8092344\r\n");
      out.write("              <br>\r\n");
      out.write("              <i class=\"fa fa-envelope-o fa-fw text-primary\"></i> informes@rcargo.com\r\n");
      out.write("              <br>\r\n");
      out.write("            </address>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <h4 class=\"text-uppercase\">\r\n");
      out.write("              Siguenos en:\r\n");
      out.write("            </h4>\r\n");
      out.write("          <!--social media icons-->\r\n");
      out.write("          <div class=\"social-media social-media-stacked\">\r\n");
      out.write("            <!--@todo: replace with company social media details-->\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-twitter fa-fw\"></i> Twitter</a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-facebook fa-fw\"></i> Facebook</a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-linkedin fa-fw\"></i> LinkedIn</a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-google-plus fa-fw\"></i> Google+</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row subfooter\">\r\n");
      out.write("        <!--@todo: replace with company copyright details-->\r\n");
      out.write("        <div class=\"col-md-7\">\r\n");
      out.write("          <p>Copyright © Rapid Cargo Encomiendas 2014-2017 </p>\r\n");
      out.write("          <div class=\"credits\">\r\n");
      out.write("            <!--\r\n");
      out.write("              All the links in the footer should remain intact.\r\n");
      out.write("              You can delete the links only if you purchased the pro version.\r\n");
      out.write("              Licensing information: https://bootstrapmade.com/license/\r\n");
      out.write("              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Flexor\r\n");
      out.write("            -->\r\n");
      out.write("            <a href=\"#\">Portal web Rapid Cargo </a> de bulletclub.com\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-5\">\r\n");
      out.write("          <ul class=\"list-inline pull-right\">\r\n");
      out.write("            <li><a href=\"#\">Terminos</a></li>\r\n");
      out.write("            <li><a href=\"#\">Privacidad</a></li>\r\n");
      out.write("            <li><a href=\"#\">Contáctanos</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"#top\" class=\"scrolltop\">Top</a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- Required JavaScript Libraries -->\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f10(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f11(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f12(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f13(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js6}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f14(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js7}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Specisifc Custom Javascript File -->\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!--Custom scripts demo background & colour switcher - OPTIONAL -->\r\n");
      out.write("  \r\n");
      out.write("  ");
      if (_jspx_meth_s_005furl_005f15(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js9}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!--Contactform script -->\r\n");
      out.write("   ");
      if (_jspx_meth_s_005furl_005f16(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${js10}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f0.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(24,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setValue("/resources/bootstrapExtranet/img/icons");
    // /WEB-INF/views/principalExtranet.jsp(24,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setVar("icons");
    int[] _jspx_push_body_count_s_005furl_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f0 = _jspx_th_s_005furl_005f0.doStartTag();
      if (_jspx_th_s_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f0.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f1 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f1.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(25,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f1.setValue("/resources/bootstrapExtranet/img");
    // /WEB-INF/views/principalExtranet.jsp(25,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f1.setVar("image");
    int[] _jspx_push_body_count_s_005furl_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f1 = _jspx_th_s_005furl_005f1.doStartTag();
      if (_jspx_th_s_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f1.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f2 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f2.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(35,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f2.setValue("/resources/bootstrapExtranet/lib/bootstrap/css/bootstrap.min.css");
    // /WEB-INF/views/principalExtranet.jsp(35,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f2.setVar("css1");
    int[] _jspx_push_body_count_s_005furl_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f2 = _jspx_th_s_005furl_005f2.doStartTag();
      if (_jspx_th_s_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f2.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f3 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f3.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(39,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f3.setValue("/resources/bootstrapExtranet/lib/font-awesome/css/font-awesome.min.css");
    // /WEB-INF/views/principalExtranet.jsp(39,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f3.setVar("css2");
    int[] _jspx_push_body_count_s_005furl_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f3 = _jspx_th_s_005furl_005f3.doStartTag();
      if (_jspx_th_s_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f3.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f4 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f4.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(41,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f4.setValue("/resources/bootstrapExtranet/lib/owlcarousel/owl.carousel.min.css");
    // /WEB-INF/views/principalExtranet.jsp(41,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f4.setVar("css3");
    int[] _jspx_push_body_count_s_005furl_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f4 = _jspx_th_s_005furl_005f4.doStartTag();
      if (_jspx_th_s_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f4.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f5 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f5.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(43,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f5.setValue("/resources/bootstrapExtranet/lib/owlcarousel/owl.theme.min.css");
    // /WEB-INF/views/principalExtranet.jsp(43,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f5.setVar("css4");
    int[] _jspx_push_body_count_s_005furl_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f5 = _jspx_th_s_005furl_005f5.doStartTag();
      if (_jspx_th_s_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f5.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f6 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f6.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(45,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f6.setValue("/resources/bootstrapExtranet/lib/owlcarousel/owl.transitions.min.css");
    // /WEB-INF/views/principalExtranet.jsp(45,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f6.setVar("css5");
    int[] _jspx_push_body_count_s_005furl_005f6 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f6 = _jspx_th_s_005furl_005f6.doStartTag();
      if (_jspx_th_s_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f6[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f6.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f6.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f7 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f7.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f7.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(49,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f7.setValue("/resources/bootstrapExtranet/css/style.css");
    // /WEB-INF/views/principalExtranet.jsp(49,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f7.setVar("maincss");
    int[] _jspx_push_body_count_s_005furl_005f7 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f7 = _jspx_th_s_005furl_005f7.doStartTag();
      if (_jspx_th_s_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f7[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f7.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f7.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f8 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f8.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f8.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(267,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f8.setValue("/resources/bootstrapExtranet/lib/jquery/jquery.min.js");
    // /WEB-INF/views/principalExtranet.jsp(267,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f8.setVar("js1");
    int[] _jspx_push_body_count_s_005furl_005f8 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f8 = _jspx_th_s_005furl_005f8.doStartTag();
      if (_jspx_th_s_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f8[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f8.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f8.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f8);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f9 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f9.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f9.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(269,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f9.setValue("/resources/bootstrapExtranet/lib/bootstrap/js/bootstrap.min.js");
    // /WEB-INF/views/principalExtranet.jsp(269,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f9.setVar("js2");
    int[] _jspx_push_body_count_s_005furl_005f9 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f9 = _jspx_th_s_005furl_005f9.doStartTag();
      if (_jspx_th_s_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f9[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f9.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f9.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f9);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f10 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f10.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f10.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(271,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f10.setValue("/resources/bootstrapExtranet/lib/owlcarousel/owl.carousel.min.js");
    // /WEB-INF/views/principalExtranet.jsp(271,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f10.setVar("js3");
    int[] _jspx_push_body_count_s_005furl_005f10 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f10 = _jspx_th_s_005furl_005f10.doStartTag();
      if (_jspx_th_s_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f10[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f10.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f10.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f10);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f11 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f11.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f11.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(273,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f11.setValue("/resources/bootstrapExtranet/lib/stellar/stellar.min.js");
    // /WEB-INF/views/principalExtranet.jsp(273,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f11.setVar("js4");
    int[] _jspx_push_body_count_s_005furl_005f11 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f11 = _jspx_th_s_005furl_005f11.doStartTag();
      if (_jspx_th_s_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f11[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f11.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f11.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f11);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f12 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f12.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f12.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(275,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f12.setValue("/resources/bootstrapExtranet/lib/waypoints/waypoints.min.js");
    // /WEB-INF/views/principalExtranet.jsp(275,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f12.setVar("js5");
    int[] _jspx_push_body_count_s_005furl_005f12 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f12 = _jspx_th_s_005furl_005f12.doStartTag();
      if (_jspx_th_s_005furl_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f12[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f12.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f12.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f12);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f13 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f13.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f13.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(277,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f13.setValue("/resources/bootstrapExtranet/lib/counterup/counterup.min.js");
    // /WEB-INF/views/principalExtranet.jsp(277,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f13.setVar("js6");
    int[] _jspx_push_body_count_s_005furl_005f13 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f13 = _jspx_th_s_005furl_005f13.doStartTag();
      if (_jspx_th_s_005furl_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f13[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f13.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f13.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f13);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f14 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f14.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f14.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(279,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f14.setValue("/resources/bootstrapExtranet/contactform/contactform.js");
    // /WEB-INF/views/principalExtranet.jsp(279,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f14.setVar("js7");
    int[] _jspx_push_body_count_s_005furl_005f14 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f14 = _jspx_th_s_005furl_005f14.doStartTag();
      if (_jspx_th_s_005furl_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f14[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f14.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f14.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f14);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f15 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f15.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f15.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(288,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f15.setValue("/resources/bootstrapExtranet/js/color-switcher.js");
    // /WEB-INF/views/principalExtranet.jsp(288,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f15.setVar("js9");
    int[] _jspx_push_body_count_s_005furl_005f15 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f15 = _jspx_th_s_005furl_005f15.doStartTag();
      if (_jspx_th_s_005furl_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f15[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f15.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f15.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f15);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_s_005furl_005f16 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_s_005furl_005f16.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f16.setParent(null);
    // /WEB-INF/views/principalExtranet.jsp(292,3) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f16.setValue("/resources/bootstrapExtranet/contactform/contactform.js");
    // /WEB-INF/views/principalExtranet.jsp(292,3) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f16.setVar("js10");
    int[] _jspx_push_body_count_s_005furl_005f16 = new int[] { 0 };
    try {
      int _jspx_eval_s_005furl_005f16 = _jspx_th_s_005furl_005f16.doStartTag();
      if (_jspx_th_s_005furl_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005furl_005f16[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005furl_005f16.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005furl_005f16.doFinally();
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005furl_005f16);
    }
    return false;
  }
}
